export enum CoverType {
  HARDCOVER = "HARDCOVER",
  SOFTCOVER = "SOFTCOVER",
  HARDCOVER_WITH_DUST_JACKET = "HARDCOVER_WITH_DUST_JACKET",
  SOFTCOVER_WITH_DUST_JACKET = "SOFTCOVER_WITH_DUST_JACKET"
}
