services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - bookcase-network

networks:
  bookcase-network:
    external:
      name: bookcase-network
